# Generated by Django 4.0.5 on 2023-03-16 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roads', '0002_alter_roads_travel_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='roads',
            name='end_point',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='roads',
            name='start_point',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
