# Generated by Django 4.0.5 on 2023-03-17 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roads', '0003_roads_end_point_roads_start_point'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.CharField(default='A00', max_length=10)),
                ('segments', models.CharField(default='E00', max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='roads',
            old_name='segment_no',
            new_name='segment',
        ),
        migrations.RemoveField(
            model_name='roads',
            name='route_no',
        ),
        migrations.AlterField(
            model_name='roads',
            name='end_point',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='roads',
            name='road_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='roads',
            name='start_point',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
