# Generated by Django 4.0.5 on 2023-03-17 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roads', '0004_route_rename_segment_no_roads_segment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='segments',
        ),
        migrations.AddField(
            model_name='roads',
            name='route',
            field=models.ManyToManyField(to='roads.route'),
        ),
    ]
