# Generated by Django 4.0.5 on 2023-03-17 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roads', '0005_remove_route_segments_roads_route'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roads',
            old_name='road_condition',
            new_name='status',
        ),
    ]
