# Generated by Django 4.0.5 on 2023-03-22 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roads', '0006_rename_road_condition_roads_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addresses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=56)),
                ('lat', models.DecimalField(decimal_places=15, default=0.0, max_digits=30)),
                ('lng', models.DecimalField(decimal_places=15, default=0.0, max_digits=30)),
            ],
        ),
        migrations.RenameField(
            model_name='roads',
            old_name='end_lon',
            new_name='end_lng',
        ),
        migrations.RenameField(
            model_name='roads',
            old_name='start_lon',
            new_name='start_lng',
        ),
    ]
