# Generated by Django 4.0.5 on 2023-03-22 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roads', '0008_alter_addresses_address_alter_addresses_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roads',
            name='start_lat',
        ),
        migrations.RemoveField(
            model_name='roads',
            name='start_lng',
        ),
        migrations.AlterField(
            model_name='roads',
            name='end_point',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='roads',
            name='route',
            field=models.ManyToManyField(blank=True, to='roads.route'),
        ),
        migrations.AlterField(
            model_name='roads',
            name='start_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='roads.addresses', to_field='address'),
        ),
    ]
