# Generated by Django 4.0.5 on 2023-03-22 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roads', '0010_remove_roads_start_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='roads',
            name='start_point',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='roads.addresses'),
        ),
        migrations.AlterField(
            model_name='addresses',
            name='address',
            field=models.CharField(max_length=128),
        ),
    ]
