# Generated by Django 4.0.5 on 2023-03-22 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roads', '0012_alter_roads_start_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roads',
            name='start_point',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.PROTECT, to='roads.addresses'),
        ),
    ]
