# Generated by Django 4.0.5 on 2023-03-30 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roads', '0021_rename_roads_segment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='route',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
