# Generated by Django 4.0.5 on 2023-04-04 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roads', '0023_alter_segment_segment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segment',
            name='route',
            field=models.ManyToManyField(blank=True, db_column='route', to='roads.route'),
        ),
        migrations.AlterField(
            model_name='segment',
            name='status',
            field=models.CharField(default='F0F0F0', max_length=6),
        ),
    ]
