# Generated by Django 4.0.5 on 2023-04-09 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roads', '0026_rename_segment_segment_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addresses',
            name='name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
