# Generated by Django 4.0.5 on 2023-04-09 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roads', '0027_addresses_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segment',
            name='end_point',
            field=models.ForeignKey(default=14, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='end_point', to='roads.addresses'),
        ),
        migrations.AlterField(
            model_name='segment',
            name='start_point',
            field=models.ForeignKey(default=14, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='start_point', to='roads.addresses'),
        ),
    ]
