# Generated by Django 4.0.5 on 2023-04-10 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roads', '0029_remove_segment_route_alter_segment_end_point_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='segment',
            name='route',
            field=models.ForeignKey(db_column='route', default=958, on_delete=django.db.models.deletion.PROTECT, to='roads.route'),
        ),
    ]
