# Generated by Django 4.0.5 on 2023-04-12 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roads', '0031_alter_segment_end_point_alter_segment_start_point'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=1, unique=True)),
            ],
        ),
    ]
