# Generated by Django 4.0.5 on 2023-04-14 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roads', '0033_segment_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='segment',
            name='category',
        ),
        migrations.AddField(
            model_name='route',
            name='category',
            field=models.ForeignKey(db_column='category', default=1, on_delete=django.db.models.deletion.PROTECT, to='roads.category'),
        ),
    ]
