# Generated by Django 4.0.5 on 2023-04-18 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roads', '0035_address_alter_segment_end_point_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='segment',
            name='end_point',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='end_point', to='roads.address'),
        ),
        migrations.AlterField(
            model_name='segment',
            name='start_point',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='start_point', to='roads.address'),
        ),
    ]
