# Generated by Django 4.0.5 on 2023-04-18 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roads', '0036_alter_address_code_alter_segment_end_point_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='code',
        ),
    ]
