# Generated by Django 4.0.5 on 2023-04-30 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roads', '0038_alter_segment_name_alter_segment_route'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
