# Generated by Django 4.0.5 on 2023-05-21 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roads', '0039_remove_route_category_delete_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='segment',
            name='index',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
