# Generated by Django 4.0.5 on 2023-05-21 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roads', '0040_segment_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='index',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
